### PR TITLE
Remove python version pinnings; add libnetcdf

### PR DESCRIPTION
**Pull request by xylar**
Add xylar as a maintainer

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I believe `libnetcdf` is explicitly used in building an internal library used in `cdtime`, so `libnetcdf` needs to be an explicit dependency and it should be pinned to a specific version.

A rerender didn't add the pinnings as I was hoping.  I'll try to figure out how to make this happen.

**Comment by xylar** [comment]
CI will fail until https://github.com/conda-forge/libcdms-feedstock/pull/26 gets merged.

**Comment by xylar** [comment]
@ocefpaf, I know how busy you are but you're also very helpful.  I'm hoping you can tell me how to either force the bot to add pinnings for libnetcdf or add them manually without breaking things.  I just added libnetcdf as a dependency, since it gets linked to a library built in this feedstock.  Things were working out of sheer luck up to now, I think.

**Comment by ocefpaf** [comment]
> @ocefpaf, I know how busy you are but you're also very helpful. I'm hoping you can tell me how to either force the bot to add pinnings for libnetcdf or add them manually without breaking things. I just added libnetcdf as a dependency, since it gets linked to a library built in this feedstock. Things were working out of sheer luck up to now, I think.

I believe that what you need is to add libnetcdf to `host` and `run` so it is properly pinned with a re-render. Let me try.

**Comment by xylar** [comment]
> I believe that what you need is to add libnetcdf to host and run so it is properly pinned with a re-render. Let me try.

Ah, of course!

**Comment by xylar** [comment]
Thanks!

**Comment by xylar** [comment]
@muryanto1, assuming you agree with these changes, would you merge this when you get a chance?

**Comment by muryanto1** [comment]
@xylar do you still need this to be merged?
I thought you are now using libnetcdf 4.6.2 till we validate cdat with libnetcdf 4.7.1 (and I am in the beginning process to rebuilt all of our packages for nightly to pick up libnetcdf).

**Comment by xylar** [comment]
@muryanto1, these changes aren't related to the libnetcdf 4.7.1 transition.  This PR is to fix errors in the recipe that are causing other issues.  The python pinning is maybe fine either way because this is not a `noarch: python` build.  But the explicit addition of libnetcdf as a dependency is important because the wrong version may be imported and built.  This needs to be merged to `cdtime` remains in sync with other pinnings on `conda-forge` regardless of whatever testing you all do for CDAT.

**Review by muryanto1 — APPROVED** [review]

**Comment by xylar** [comment]
@muryanto1, I think you should probably just merge this.  I doubt the other requested reviewers will actually review at this point.  They are chosen automatically by GitHub because, in the past, they have edited files I modified.

**Pull request merged**
